import HeaderLeftButton from '@/components/Header/HeaderLeftButton';
import HeroRightImg from '@/components/Hero/HeroRightImg';
import Main from '@/components/Layout/Main';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Hundred Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <HeaderLeftButton />
        <HeroRightImg />
      </Main>
    </>
  );
}
